import { Image as ImageIcon } from 'lucide-react';

export function Gallery() {
  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-white">Gallery</h1>
        <p className="text-muted-foreground">Visual content generated by your agents</p>
      </div>
      
      {/* Empty State */}
      <div className="bg-card border border-border rounded-xl p-12 text-center">
        <div className="w-16 h-16 rounded-full bg-card border border-border flex items-center justify-center mx-auto mb-4">
          <ImageIcon className="w-8 h-8 text-muted-foreground" />
        </div>
        <h3 className="text-lg font-semibold text-white mb-2">No images yet</h3>
        <p className="text-muted-foreground max-w-md mx-auto">
          Images generated by your agents will appear here. Ask Arturo or other visual agents to create content.
        </p>
      </div>
    </div>
  );
}
